"""
core/sample_data.py
===================
Loads the bundled Dalby sample dataset when SILO is unavailable.

The parquet file is committed to the repo at sample_data/dalby_sample.parquet
and generated by running fetch_sample_data.py once locally when SILO is up.
The returned DataFrame is in exactly the same format as ensure_climate_cached
returns (columns: rain, tmax, tmin, epan, radiation, vp, tmean; DatetimeIndex).
"""

import json
from pathlib import Path
import pandas as pd

_HERE = Path(__file__).resolve().parent.parent
_SAMPLE_DIR = _HERE / "sample_data"
_PARQUET = _SAMPLE_DIR / "dalby_sample.parquet"
_META_JSON = _SAMPLE_DIR / "dalby_station.json"


def sample_data_available() -> bool:
    """True if the bundled sample dataset exists and is readable."""
    return _PARQUET.exists() and _META_JSON.exists()


def load_sample_station() -> dict:
    """
    Return station metadata dict for the bundled sample site,
    in the same format as silo.search_stations() returns per-station.
    """
    if not _META_JSON.exists():
        raise FileNotFoundError(
            f"Sample station metadata not found at {_META_JSON}. "
            "Run fetch_sample_data.py first."
        )
    return json.loads(_META_JSON.read_text())


def load_sample_climate() -> pd.DataFrame:
    """
    Return the bundled Dalby climate DataFrame, same schema as
    ensure_climate_cached: columns rain/tmax/tmin/epan/radiation/vp/tmean,
    DatetimeIndex.
    """
    if not _PARQUET.exists():
        raise FileNotFoundError(
            f"Sample climate data not found at {_PARQUET}. "
            "Run fetch_sample_data.py first."
        )
    df = pd.read_parquet(_PARQUET)
    # Ensure tmean is present (may have been computed at fetch time)
    if "tmean" not in df.columns and "tmax" in df.columns and "tmin" in df.columns:
        df["tmean"] = (df["tmax"] + df["tmin"]) / 2.0
    return df


def sample_date_range() -> tuple:
    """Return (start_date, end_date) of the bundled sample as date objects."""
    df = load_sample_climate()
    return df.index[0].date(), df.index[-1].date()
